! Title: Custom Brave Filter List (Prioritized from DDG TDS)
! Description: Automatically generated list of ~200 tracking/ad domains based on DuckDuckGo TDS (extension-mv3-tds.json structure). Prioritized by category and prevalence. Excludes known CDNs and potential site breakers.
! Source: extension-mv3-tds.json (structure from https://raw.githubusercontent.com/duckduckgo/tracker-blocklists/refs/heads/main/web/v6/extension-mv3-tds.json)
! Updated: 2025-04-17 12:17:33 
! Domain Count: 200
!
! WARNING: Use at your own risk. While efforts were made to avoid breaking sites, some breakage is always possible with filter lists.
!-------------------------------------------------------------------


! --- Manually added rules for major platforms (blocking off-site tracking) ---
||connect.facebook.net^
||facebook.com^$domain=~facebook.com|~fb.com|~fbcdn.net|~messenger.com|~instagram.com|~whatsapp.com
||google-analytics.com^
||analytics.google.com^
||adservice.google.com^
||googletagmanager.com^
||googlesyndication.com^
||doubleclick.net^
||googleadservices.com^
||google.com/ads^
||google.com/pagead^
||youtube.com/api/stats/atr^^
||youtube.com/api/stats/playback^^
||youtube.com/api/stats/watchtime^^
||ads.linkedin.com^
||linkedin.com/li/track^
||linkedin.com^$domain=~linkedin.com|~licdn.com
||platform.twitter.com^
||ads-twitter.com^
||twitter.com^$domain=~twitter.com|~twimg.com
||ads.pinterest.com^
||pinterest.com^$domain=~pinterest.com|~pinimg.com
||bat.bing.com^
||ads.microsoft.com^

! --- Automatically generated rules (Top {len(top_domains)} prioritized) ---
||pubads.g.doubleclick.net^
||securepubads.g.doubleclick.net^
||doubleclick.net^
||g.doubleclick.net^
||google-analytics.com^
||googlesyndication.com^
||pagead2.googlesyndication.com^
||acdn.adnxs.com^
||adnxs.com^
||ib.adnxs.com^
||adsrvr.org^
||bing.com^
||micro.rubiconproject.com^
||rubiconproject.com^
||tapad.com^
||pubmatic.com^
||yahoo.com^
||casalemedia.com^
||rlcdn.com^
||criteo.com^
||openx.net^
||ad.crwdcntrl.net^
||crwdcntrl.net^
||amazon-adsystem.com^
||bidswitch.net^
||stackadapt.com^
||3lift.com^
||liadm.com^
||smartadserver.com^
||turn.com^
||lijit.com^
||demdex.net^
||id5-sync.com^
||1rx.io^
||33across.com^
||sharethrough.com^
||creativecdn.com^
||bidr.io^
||adform.net^
||media.net^
||contextual.media.net^
||contextweb.com^
||outbrain.com^
||simpli.fi^
||dotomi.com^
||ipredictive.com^
||quantserve.com^
||unrulymedia.com^
||pippio.com^
||sitescout.com^
||thrtle.com^
||zemanta.com^
||agkn.com^
||gumgum.com^
||yieldmo.com^
||sonobi.com^
||smaato.net^
||rfihub.com^
||360yield.com^
||googleadservices.com^
||stickyadstv.com^
||loopme.me^
||teads.tv^
||postrelease.com^
||deepintent.com^
||taboola.com^
||criteo.net^
||semasio.net^
||intentiq.com^
||2mdn.net^
||mathtag.com^
||mediavine.com^
||kargo.com^
||indexww.com^
||adentifi.com^
||tynt.com^
||mfadsrvr.com^
||omnitagjs.com^
||eyeota.net^
||undertone.com^
||exelator.com^
||mookie1.com^
||w55c.net^
||imrworldwide.com^
||secure-drm.imrworldwide.com^
||ads-twitter.com^
||socdm.com^
||klaviyo.com^
||t.co^
||tremorhub.com^
||adsafeprotected.com^
||static.adsafeprotected.com^
||adobedtm.com^
||assets.adobedtm.com^
||rkdms.com^
||bfmio.com^
||ib-ibi.com^
||googletagservices.com^
||adkernel.com^
||technoratimedia.com^
||rqtrk.eu^
||flashtalking.com^
||ml314.com^
||betweendigital.com^
||snow.com.ssl.d2.sc.omtrdc.net^
||tt.omtrdc.net^
||omtrdc.net^
||adthrive.com^
||tribalfusion.com^
||mxptint.net^
||media6degrees.com^
||app.hubspot.com^
||hubspot.com^
||forms.hubspot.com^
||emxdgt.com^
||sc-static.net^
||bttrack.com^
||sharethis.com^
||blismedia.com^
||doubleverify.com^
||money.yandex.ru^
||static-maps.yandex.ru^
||geocode-maps.yandex.ru^
||frontend.vh.yandex.ru^
||img-fotki.yandex.ru^
||pay.yandex.ru^
||api-maps.yandex.ru^
||yandex.ru^
||ctnsnet.com^
||adroll.com^
||adgrx.com^
||acuityplatform.com^
||static.addtoany.com^
||addtoany.com^
||attn.tv^
||chartbeat.com^
||appier.net^
||company-target.com^
||pro-market.net^
||tags.tiqcdn.com^
||tiqcdn.com^
||hsadspixel.net^
||segment.com^
||revcontent.com^
||yotpo.com^
||admedo.com^
||e-planning.net^
||skimresources.com^
||adition.com^
||segment.io^
||mgid.com^
||clickagy.com^
||admixer.net^
||marketo.net^
||mktoresp.com^
||dwin1.com^
||cpx.to^
||bounceexchange.com^
||tvsquared.com^
||springserve.com^
||cdn-images.mailchimp.com^
||mailchimp.com^
||gallery.mailchimp.com^
||creative-serving.com^
||adlightning.com^
||securedvisit.com^
||ezoic.net^
||sundaysky.com^
||dtscout.com^
||owneriq.net^
||storygize.net^
||sail-horizon.com^
||ak.sail-horizon.com^
||tealiumiq.com^
||tsyndicate.com^
||trackcmp.net^
||cxense.com^
||img.en25.com^
||en25.com^
||ntv.io^
||basis.net^
||ispot.tv^
||eloqua.com^
||igodigital.com^
||pardot.com^
||go.pardot.com^
||impactradius-event.com^
||affec.tv^
||cdn.blueconic.net^
||blueconic.net^
||cdn.listrakbi.com^
||listrakbi.com^
||adswizz.com^
||weborama.fr^
||truoptik.com^
||sascdn.com^
||nexus.ensighten.com^
||ensighten.com^
||quora.com^
||yahoo.co.jp^
